### ISSUE TITLE
I don't find the result of DGUNet on the DND benchmark

### ISSUE THREAD

**Issue by IDKiro** [MC-E/Deep-Generalized-Unfolding-Networks-for-Image-Restoration#1]
It's an amazing work!
Training the denoising network to 40.12dB using only the SIDD dataset seems to be the best current performance. 
I don't understand why the results are hidden on DND.

**Comment by IDKiro** [comment]
In addition, FGDM does not seem to be suitable for image denoising because the noise degradation process is not deterministic (not `Ax` but `+ n`)?

**Comment by MC-E** [comment]
Thanks for your attention and valuable suggestion! We have updated the evaluation for DND. In real-world scenarios, image denoising is not only related to additive noise (i.e., A!=I).

**Comment by IDKiro** [comment]
Thanks for your answer!
