### ISSUE TITLE
compressive sensing数据集与论文中有差异

### ISSUE THREAD

**Issue by yhao-z** [MC-E/Deep-Generalized-Unfolding-Networks-for-Image-Restoration#5]
您好！
* 您论文中指出在compressive sensing任务中，只用了BSD400作为训练集
> or this application, we choose the widely used **BSD400 dataset [43]** as the training data and evaluate each method on Set11 [35] and BSD68 [43] test sets.
* 但是您实际代码中提供的训练集确是DIV2K800+BSD400共计1200幅图像的混合数据集
* 那么您文章中的所有对比方法的PSNR指标结果也是用混合训练集再训练的结果吗？
* 您是否用混合数据集对其它对比方法进行了二次训练？

**Comment by MC-E** [comment]
您好！我们在CS任务上使用的训练集是DIV2K800+BSD400，其他方法我们没有进行二次训练。

**Comment by yhao-z** [comment]
好的，非常感谢！
